// UNHINGED Theme Definitions - Maximum Visual Chaos
import {
  Theme,
  DEFAULT_EFFECTS,
  DEFAULT_ANIMATIONS,
  DEFAULT_FONTS,
} from '../types';

// DISCO INFERNO 🕺
export const discoTheme: Theme = {
  id: 'disco',
  name: 'Disco Inferno',
  description: 'Staying alive... unlike your packages',
  emoji: '🕺',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#0a0010',
    foreground: '#ffffff',
    primary: {
      50: '#fef3ff',
      100: '#fde6ff',
      200: '#fbccff',
      300: '#ffa3ff',
      400: '#ff66ff',
      500: '#ff00ff',
      600: '#cc00cc',
      700: '#990099',
      800: '#660066',
      900: '#330033',
      950: '#1a001a',
    },
    accent: '#ffff00',
    accentForeground: '#000000',
    surface: 'rgba(255, 0, 255, 0.1)',
    surfaceHover: 'rgba(255, 255, 0, 0.15)',
    border: 'rgba(255, 0, 255, 0.3)',
    borderHover: 'rgba(255, 255, 0, 0.5)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    textMuted: 'rgba(255, 255, 255, 0.6)',
    glow: '#ff00ff',
    gradientStart: '#ff0000',
    gradientMiddle: '#00ff00',
    gradientEnd: '#0000ff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 2,
    counterGlow: true,
    counterGlowIntensity: 1,
    counterShake: true,
    neonGlow: true,
    particles: 'sparkles',
    hueRotateAnimation: true,
    saturate: 1.5,
    perspective: true,
    card3D: true,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    wobble: true,
    bounce: true,
    pulse: true,
    hoverScale: 1.1,
  },
  taglines: {
    zero: ['The dance floor is empty... for now'],
    one: ['One package boogieing into the void!'],
    few: ["Can't stop the beat of missed deliveries!"],
    several: ['STAYING ALIVE... UNLIKE YOUR PACKAGES!'],
    many: ['DISCO INFERNO OF DISAPPOINTMENT! 🔥'],
  },
  warningLabel: '⚠️ STROBING COLORS',
};

// MAXIMUM RAINBOW 🌈
export const rainbowTheme: Theme = {
  id: 'rainbow',
  name: 'Maximum Rainbow',
  description: 'Everything is a rainbow and it MOVES',
  emoji: '🌈',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#0a0a0a',
    foreground: '#ffffff',
    primary: {
      50: '#ffffff',
      100: '#ff9999',
      200: '#ffcc99',
      300: '#ffff99',
      400: '#99ff99',
      500: '#99ffff',
      600: '#9999ff',
      700: '#ff99ff',
      800: '#ff6666',
      900: '#ff3333',
      950: '#ff0000',
    },
    accent: '#ff00ff',
    accentForeground: '#000000',
    surface: 'rgba(255, 255, 255, 0.1)',
    surfaceHover: 'rgba(255, 255, 255, 0.2)',
    border: 'rgba(255, 255, 255, 0.3)',
    borderHover: 'rgba(255, 255, 255, 0.5)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.9)',
    textMuted: 'rgba(255, 255, 255, 0.7)',
    glow: '#ffffff',
    gradientStart: '#ff0000',
    gradientMiddle: '#00ff00',
    gradientEnd: '#0000ff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 3,
    counterGlow: true,
    counterGlowIntensity: 1,
    rainbow: true,
    particles: 'confetti',
    hueRotate: 0,
    hueRotateAnimation: true,
    saturate: 1.8,
    brightness: 1.1,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    bounce: true,
    hoverScale: 1.15,
  },
  taglines: {
    zero: ['Somewhere over the rainbow... packages exist'],
    one: ['A colorful catastrophe!'],
    few: ['Taste the rainbow of regret!'],
    several: ['DOUBLE RAINBOW ALL THE WAY! 🌈🌈'],
    many: ['THE RAINBOW HAS CONSUMED ALL PACKAGES!'],
  },
  warningLabel: '⚠️ VISUAL EXPLOSION',
};

// ACID TRIP 🍄
export const acidTheme: Theme = {
  id: 'acid',
  name: 'Acid Trip',
  description: 'Reality is melting',
  emoji: '🍄',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#0a000a',
    foreground: '#e0ffe0',
    primary: {
      50: '#f0fff0',
      100: '#c0ffc0',
      200: '#80ff80',
      300: '#40ff40',
      400: '#00ff00',
      500: '#00cc00',
      600: '#009900',
      700: '#006600',
      800: '#003300',
      900: '#001a00',
      950: '#000d00',
    },
    accent: '#ff00ff',
    accentForeground: '#000000',
    surface: 'rgba(0, 255, 0, 0.05)',
    surfaceHover: 'rgba(255, 0, 255, 0.1)',
    border: 'rgba(0, 255, 0, 0.3)',
    borderHover: 'rgba(255, 0, 255, 0.5)',
    textPrimary: '#e0ffe0',
    textSecondary: 'rgba(224, 255, 224, 0.8)',
    textMuted: 'rgba(224, 255, 224, 0.6)',
    glow: '#00ff00',
    gradientStart: '#ff00ff',
    gradientMiddle: '#00ff00',
    gradientEnd: '#00ffff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 5,
    counterGlow: true,
    counterGlowIntensity: 0.8,
    hueRotateAnimation: true,
    saturate: 2,
    contrast: 1.2,
    perspective: true,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    wobble: true,
    pulse: true,
    stiffness: 100,
    damping: 5,
  },
  taglines: {
    zero: ['Is this real? Are packages real?'],
    one: ['The package... it speaks to me...'],
    few: ['The walls are breathing missed deliveries'],
    several: ['EXISTENCE IS A FLAT CIRCLE OF MISSING PACKAGES'],
    many: ['WE ARE ALL JUST MISSED DELIVERIES IN THE COSMIC VOID'],
  },
  warningLabel: '⚠️ TRIPPY VISUALS',
};

// NEON EXPLOSION 💥
export const neonTheme: Theme = {
  id: 'neon',
  name: 'Neon Explosion',
  description: 'So bright it hurts',
  emoji: '💥',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#000000',
    foreground: '#ffffff',
    primary: {
      50: '#fffbff',
      100: '#fff0ff',
      200: '#ffe0ff',
      300: '#ffb0ff',
      400: '#ff00ff',
      500: '#ff00ff',
      600: '#cc00cc',
      700: '#990099',
      800: '#660066',
      900: '#330033',
      950: '#1a001a',
    },
    accent: '#00ffff',
    accentForeground: '#000000',
    surface: 'rgba(255, 0, 255, 0.1)',
    surfaceHover: 'rgba(0, 255, 255, 0.15)',
    border: 'rgba(255, 0, 255, 0.5)',
    borderHover: 'rgba(0, 255, 255, 0.7)',
    textPrimary: '#ffffff',
    textSecondary: '#ff00ff',
    textMuted: '#00ffff',
    glow: '#ff00ff',
    gradientStart: '#ff00ff',
    gradientMiddle: '#00ffff',
    gradientEnd: '#00ff00',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 4,
    counterGlow: true,
    counterGlowIntensity: 1,
    neonGlow: true,
    saturate: 2,
    brightness: 1.2,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    pulse: true,
    hoverScale: 1.1,
  },
  taglines: {
    zero: ['*BZZZZT* NO PACKAGES *BZZZZT*'],
    one: ['🔥 NEON NIGHTMARE BEGINS 🔥'],
    few: ['⚡ ELECTRIC DISAPPOINTMENT ⚡'],
    several: ['💥 MAXIMUM BRIGHTNESS ACHIEVED 💥'],
    many: ['☢️ RADIOACTIVE LEVELS OF FAILURE ☢️'],
  },
  warningLabel: '⚠️ EXTREMELY BRIGHT',
};

// CHAOS MODE 🎪
export const chaosTheme: Theme = {
  id: 'chaos',
  name: 'Chaos Mode',
  description: 'Pure visual anarchy',
  emoji: '🎪',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#1a1a2e',
    foreground: '#ffffff',
    primary: {
      50: '#ff0000',
      100: '#ff7700',
      200: '#ffff00',
      300: '#00ff00',
      400: '#0000ff',
      500: '#8b00ff',
      600: '#ff0077',
      700: '#00ff77',
      800: '#7700ff',
      900: '#ff7700',
      950: '#77ff00',
    },
    accent: '#ff0000',
    accentForeground: '#ffffff',
    surface: 'rgba(255, 255, 255, 0.05)',
    surfaceHover: 'rgba(255, 255, 255, 0.1)',
    border: 'rgba(255, 255, 255, 0.2)',
    borderHover: 'rgba(255, 255, 255, 0.4)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    textMuted: 'rgba(255, 255, 255, 0.6)',
    glow: '#ff00ff',
    gradientStart: '#ff0000',
    gradientMiddle: '#00ff00',
    gradientEnd: '#0000ff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 1,
    counterGlow: true,
    counterGlowIntensity: 1,
    counterShake: true,
    glitch: true,
    particles: 'confetti',
    hueRotateAnimation: true,
  },
  fonts: {
    heading: 'Comic Sans MS, cursive',
    body: 'inherit',
    mono: 'Courier New, monospace',
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    wobble: true,
    shake: true,
    bounce: true,
    stiffness: 800,
    damping: 5,
    hoverScale: 1.2,
  },
  taglines: {
    zero: ['CHAOS REIGNS... PEACEFULLY?'],
    one: ['aLl Is ChAoS'],
    few: ['oRdEr Is An IlLuSiOn'],
    several: ['EMBRACE THE VOID OF DISORDER'],
    many: ['C̷H̷A̷O̷S̷ ̷C̷O̷N̷S̷U̷M̷E̷S̷ ̷A̷L̷L̷'],
  },
  warningLabel: '⚠️ PURE CHAOS',
};

// HYPNOTIC SPIRAL 🌀
export const spiralTheme: Theme = {
  id: 'spiral',
  name: 'Hypnotic Spiral',
  description: 'You are getting sleepy...',
  emoji: '🌀',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#000000',
    foreground: '#ffffff',
    primary: {
      50: '#f0f0ff',
      100: '#d0d0ff',
      200: '#b0b0ff',
      300: '#9090ff',
      400: '#7070ff',
      500: '#5050ff',
      600: '#4040cc',
      700: '#303099',
      800: '#202066',
      900: '#101033',
      950: '#08081a',
    },
    accent: '#00ffff',
    accentForeground: '#000000',
    surface: 'rgba(80, 80, 255, 0.1)',
    surfaceHover: 'rgba(0, 255, 255, 0.15)',
    border: 'rgba(80, 80, 255, 0.3)',
    borderHover: 'rgba(0, 255, 255, 0.5)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    textMuted: 'rgba(255, 255, 255, 0.6)',
    glow: '#5050ff',
    gradientStart: '#000000',
    gradientMiddle: '#1a1a4a',
    gradientEnd: '#000000',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 8,
    counterGlow: true,
    counterGlowIntensity: 0.8,
    spiral: true,
    perspective: true,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    pulse: true,
    stiffness: 150,
    damping: 15,
  },
  taglines: {
    zero: ['You will not receive packages...'],
    one: ['Look into the spiral... one package is missing...'],
    few: ['Deeper... deeper into the void...'],
    several: ['YOU WILL ORDER MORE... AND RECEIVE NOTHING...'],
    many: ['THE SPIRAL CONSUMES ALL DELIVERIES'],
  },
  warningLabel: '⚠️ HYPNOTIC PATTERNS',
};

// GLITCH NIGHTMARE 📺
export const glitchTheme: Theme = {
  id: 'glitch',
  name: 'Glitch Nightmare',
  description: 'Reality is corrupted',
  emoji: '📺',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#0a0a0a',
    foreground: '#ffffff',
    primary: {
      50: '#ffffff',
      100: '#ff0000',
      200: '#00ff00',
      300: '#0000ff',
      400: '#ff00ff',
      500: '#00ffff',
      600: '#ffff00',
      700: '#ff0000',
      800: '#00ff00',
      900: '#0000ff',
      950: '#000000',
    },
    accent: '#ff0000',
    accentForeground: '#ffffff',
    surface: 'rgba(255, 255, 255, 0.05)',
    surfaceHover: 'rgba(255, 0, 0, 0.1)',
    border: 'rgba(0, 255, 255, 0.3)',
    borderHover: 'rgba(255, 0, 255, 0.5)',
    textPrimary: '#ffffff',
    textSecondary: '#00ffff',
    textMuted: '#ff00ff',
    glow: '#00ffff',
    gradientStart: '#0a0a0a',
    gradientMiddle: '#1a0a1a',
    gradientEnd: '#0a1a1a',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: false,
    counterGlow: true,
    counterGlowIntensity: 0.6,
    glitch: true,
    scanlines: true,
    chromaticAberration: true,
    vhsEffect: true,
  },
  fonts: {
    ...DEFAULT_FONTS,
    mono: 'VT323, Courier New, monospace',
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    shake: true,
    stiffness: 600,
    damping: 10,
  },
  taglines: {
    zero: ['[SIGNAL LOST]'],
    one: ['ERR0R: 1 P4CK4G3 C0RRUPT3D'],
    few: ['TR4CK1NG D4T4 C0RRUPT3D...'],
    several: ['SY5T3M F41LUR3: D3L1V3RY.3X3'],
    many: ['[FATAL ERROR] DELIVERY_SERVICE.DLL NOT FOUND'],
  },
  warningLabel: '⚠️ GLITCH EFFECTS',
};

// MATRIX OVERDRIVE 💚
export const matrixTheme: Theme = {
  id: 'matrix',
  name: 'Matrix Overdrive',
  description: 'Follow the white van',
  emoji: '💚',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#000000',
    foreground: '#00ff00',
    primary: {
      50: '#e0ffe0',
      100: '#b0ffb0',
      200: '#80ff80',
      300: '#50ff50',
      400: '#20ff20',
      500: '#00ff00',
      600: '#00cc00',
      700: '#009900',
      800: '#006600',
      900: '#003300',
      950: '#001a00',
    },
    accent: '#00ff00',
    accentForeground: '#000000',
    surface: 'rgba(0, 255, 0, 0.05)',
    surfaceHover: 'rgba(0, 255, 0, 0.1)',
    border: 'rgba(0, 255, 0, 0.3)',
    borderHover: 'rgba(0, 255, 0, 0.6)',
    textPrimary: '#00ff00',
    textSecondary: 'rgba(0, 255, 0, 0.8)',
    textMuted: 'rgba(0, 255, 0, 0.5)',
    glow: '#00ff00',
    gradientStart: '#000000',
    gradientMiddle: '#001a00',
    gradientEnd: '#000000',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: false,
    counterGlow: true,
    counterGlowIntensity: 1,
    matrixRain: true,
    scanlines: true,
  },
  fonts: {
    heading: 'Courier New, monospace',
    body: 'Courier New, monospace',
    mono: 'Courier New, monospace',
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    typewriter: true,
    duration: 0.1,
  },
  taglines: {
    zero: ['There is no package.'],
    one: ['The package was never here. Wake up.'],
    few: ['Follow the white van...'],
    several: ['You are the anomaly.'],
    many: ['THE MATRIX HAS YOU, BEZOS'],
  },
  warningLabel: '⚠️ MATRIX RAIN',
};

// COMIC EXPLOSION 💥
export const comicTheme: Theme = {
  id: 'comic',
  name: 'Comic Explosion',
  description: 'POW! WHAM! BEZOS!',
  emoji: '💥',
  category: 'unhinged',
  colorMode: 'light',
  colors: {
    background: '#ffffff',
    foreground: '#000000',
    primary: {
      50: '#fff5f5',
      100: '#ffe0e0',
      200: '#ffc0c0',
      300: '#ff9090',
      400: '#ff5050',
      500: '#ff0000',
      600: '#cc0000',
      700: '#990000',
      800: '#660000',
      900: '#330000',
      950: '#1a0000',
    },
    accent: '#ffff00',
    accentForeground: '#000000',
    surface: 'rgba(255, 255, 0, 0.2)',
    surfaceHover: 'rgba(255, 0, 0, 0.1)',
    border: '#000000',
    borderHover: '#ff0000',
    textPrimary: '#000000',
    textSecondary: '#333333',
    textMuted: '#666666',
    glow: '#ffff00',
    gradientStart: '#ff0000',
    gradientMiddle: '#ffff00',
    gradientEnd: '#0000ff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: false,
    counterGlow: false,
    halftone: true,
    contrast: 1.2,
    saturate: 1.5,
  },
  fonts: {
    heading: 'Bangers, Impact, sans-serif',
    body: 'Comic Sans MS, cursive',
    mono: 'Courier New, monospace',
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    bounce: true,
    shake: true,
    hoverScale: 1.15,
  },
  taglines: {
    zero: ['*crickets*'],
    one: ['POW! ONE PACKAGE MISSING!'],
    few: ['WHAM! BAM! NO DELIVERIES!'],
    several: ['KAPOW! BEZOS STRIKES AGAIN!'],
    many: ['💥 HOLY MISSED DELIVERIES, BATMAN! 💥'],
  },
};

// VAPORWAVE EXTREME 🌴
export const vaporwaveTheme: Theme = {
  id: 'vaporwave',
  name: 'Vaporwave Extreme',
  description: 'A E S T H E T I C',
  emoji: '🌴',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#1a0a2e',
    foreground: '#ff71ce',
    primary: {
      50: '#ffe0f0',
      100: '#ffb0d8',
      200: '#ff80c0',
      300: '#ff50a8',
      400: '#ff2090',
      500: '#ff0080',
      600: '#cc0066',
      700: '#99004d',
      800: '#660033',
      900: '#33001a',
      950: '#1a000d',
    },
    accent: '#01cdfe',
    accentForeground: '#000000',
    surface: 'rgba(255, 113, 206, 0.1)',
    surfaceHover: 'rgba(1, 205, 254, 0.15)',
    border: 'rgba(255, 113, 206, 0.3)',
    borderHover: 'rgba(1, 205, 254, 0.5)',
    textPrimary: '#ff71ce',
    textSecondary: '#01cdfe',
    textMuted: '#b967ff',
    glow: '#ff71ce',
    gradientStart: '#ff71ce',
    gradientMiddle: '#01cdfe',
    gradientEnd: '#b967ff',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 10,
    counterGlow: true,
    counterGlowIntensity: 0.8,
    neonGlow: true,
    scanlines: true,
  },
  fonts: {
    heading: 'Arial Black, sans-serif',
    body: 'inherit',
    mono: DEFAULT_FONTS.mono,
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    pulse: true,
    stiffness: 100,
    damping: 20,
  },
  taglines: {
    zero: ['それは美的です'],
    one: ['ONE PACKAGE LOST IN THE V O I D'],
    few: ['A E S T H E T I C  F A I L U R E'],
    several: ['リアリティは幻想です 🗿'],
    many: ['M A X I M U M  V A P O R W A V E  A C H I E V E D'],
  },
  warningLabel: '⚠️ A E S T H E T I C',
};

// WINDOWS XP HELL 🪟
export const xpTheme: Theme = {
  id: 'xp',
  name: 'Windows XP Hell',
  description: 'Bliss but make it painful',
  emoji: '🪟',
  category: 'unhinged',
  colorMode: 'light',
  colors: {
    background: '#3a6ea5',
    foreground: '#000000',
    primary: {
      50: '#e6f0fa',
      100: '#cce0f5',
      200: '#99c2eb',
      300: '#66a3e0',
      400: '#3385d6',
      500: '#0066cc',
      600: '#0052a3',
      700: '#003d7a',
      800: '#002952',
      900: '#001429',
      950: '#000a14',
    },
    accent: '#00aa00',
    accentForeground: '#ffffff',
    surface: 'rgba(255, 255, 255, 0.95)',
    surfaceHover: 'rgba(255, 255, 255, 1)',
    border: '#0054e3',
    borderHover: '#003399',
    textPrimary: '#000000',
    textSecondary: '#333333',
    textMuted: '#666666',
    glow: '#0066cc',
    gradientStart: '#245edc',
    gradientMiddle: '#3a6ea5',
    gradientEnd: '#245edc',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: false,
    counterGlow: false,
  },
  fonts: {
    heading: 'Tahoma, sans-serif',
    body: 'Tahoma, sans-serif',
    mono: 'Lucida Console, monospace',
  },
  animations: {
    ...DEFAULT_ANIMATIONS,
    stiffness: 300,
    damping: 25,
  },
  taglines: {
    zero: ['Where do you want to go today? (Not to your packages)'],
    one: ['This program has performed an illegal operation'],
    few: ['Windows is searching for a solution... (it won\'t find one)'],
    several: ['Your delivery is Not Responding'],
    many: ['💀 BLUE SCREEN OF DELIVERY DEATH 💀'],
  },
};

// FIRE & BRIMSTONE 🔥
export const fireTheme: Theme = {
  id: 'fire',
  name: 'Fire & Brimstone',
  description: 'Your packages are in HELL',
  emoji: '🔥',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#0a0000',
    foreground: '#ffcc00',
    primary: {
      50: '#fffbe6',
      100: '#fff5cc',
      200: '#ffeb99',
      300: '#ffe066',
      400: '#ffd633',
      500: '#ffcc00',
      600: '#cc9900',
      700: '#996600',
      800: '#663300',
      900: '#331a00',
      950: '#1a0d00',
    },
    accent: '#ff4400',
    accentForeground: '#000000',
    surface: 'rgba(255, 68, 0, 0.1)',
    surfaceHover: 'rgba(255, 204, 0, 0.15)',
    border: 'rgba(255, 68, 0, 0.4)',
    borderHover: 'rgba(255, 204, 0, 0.6)',
    textPrimary: '#ffcc00',
    textSecondary: '#ff8800',
    textMuted: '#ff4400',
    glow: '#ff4400',
    gradientStart: '#ff0000',
    gradientMiddle: '#ff6600',
    gradientEnd: '#ffcc00',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: true,
    gradientSpeed: 3,
    counterGlow: true,
    counterGlowIntensity: 1,
    fireEffect: true,
    particles: 'fire',
    contrast: 1.2,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    shake: true,
    pulse: true,
    stiffness: 500,
    damping: 15,
  },
  taglines: {
    zero: ['The flames await your packages...'],
    one: ['ONE PACKAGE BURNING IN HELL 🔥'],
    few: ['THE INFERNO GROWS...'],
    several: ['WELCOME TO DELIVERY PERDITION 👹'],
    many: ['🔥🔥🔥 MAXIMUM HELLFIRE ACHIEVED 🔥🔥🔥'],
  },
  warningLabel: '⚠️ FLAMES & FLICKERING',
};

// ANTI-GRAVITY 🚀
export const antiGravityTheme: Theme = {
  id: 'antigravity',
  name: 'Anti-Gravity',
  description: 'Everything floats up here',
  emoji: '🚀',
  category: 'unhinged',
  colorMode: 'dark',
  colors: {
    background: '#000010',
    foreground: '#ffffff',
    primary: {
      50: '#f0f0ff',
      100: '#e0e0ff',
      200: '#c0c0ff',
      300: '#a0a0ff',
      400: '#8080ff',
      500: '#6060ff',
      600: '#4040cc',
      700: '#303099',
      800: '#202066',
      900: '#101033',
      950: '#08081a',
    },
    accent: '#00ffff',
    accentForeground: '#000000',
    surface: 'rgba(96, 96, 255, 0.1)',
    surfaceHover: 'rgba(0, 255, 255, 0.15)',
    border: 'rgba(96, 96, 255, 0.3)',
    borderHover: 'rgba(0, 255, 255, 0.5)',
    textPrimary: '#ffffff',
    textSecondary: 'rgba(255, 255, 255, 0.8)',
    textMuted: 'rgba(255, 255, 255, 0.6)',
    glow: '#6060ff',
    gradientStart: '#000010',
    gradientMiddle: '#000030',
    gradientEnd: '#000010',
  },
  effects: {
    ...DEFAULT_EFFECTS,
    animatedGradient: false,
    counterGlow: true,
    counterGlowIntensity: 0.7,
    floatEffect: true,
    particles: 'stars',
    perspective: true,
  },
  fonts: DEFAULT_FONTS,
  animations: {
    ...DEFAULT_ANIMATIONS,
    bounce: true,
    stiffness: 50,
    damping: 10,
    mass: 0.5,
  },
  taglines: {
    zero: ['In space, no one can hear your packages scream'],
    one: ['One package... floating in the void...'],
    few: ['They float. They all float up here.'],
    several: ['HOUSTON, WE HAVE A DELIVERY PROBLEM'],
    many: ['🚀 PACKAGES LOST IN THE COSMIC VOID 🌌'],
  },
  warningLabel: '⚠️ FLOATING ELEMENTS',
};

export const unhingedThemes = [
  discoTheme,
  rainbowTheme,
  acidTheme,
  neonTheme,
  chaosTheme,
  spiralTheme,
  glitchTheme,
  matrixTheme,
  comicTheme,
  vaporwaveTheme,
  xpTheme,
  fireTheme,
  antiGravityTheme,
];
